{% set version = "3.0.7" %}

package:
  name: jupyterlab_widgets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_widgets/jupyterlab_widgets-{{ version }}.tar.gz
  sha256: c3a50ed5bf528a0c7a869096503af54702f86dda1db469aee1c92dc0c01b43ca
build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - jupyter-packaging
  run:
    - python >=3.7
  run_constrained:
    - jupyterlab >=3,<5

test:
  imports:
    - jupyterlab_widgets
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "@jupyter-widgets/jupyterlab-manager.*OK" labextensions
  requires:
    - jupyterlab
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/jupyter-widgets/ipywidgets
  summary: JupyterLab extension providing HTML widgets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jasongrout
    - SylvainCorlay
    - martinRenou
    - jtpio
    - bollwyvl
